### PR TITLE
Fix for #199 - Circular references in JSON schemas

### PR DESCRIPTION
**Pull request by santam85**
Hi @zaggino, we took a stab at fixing it. We use this library internally in our company and we ran into this circular reference issue lately, it's blocking us big time, so let us know if it needs further improvement, otherwise we'd appreciate if you could release it soon!

### CODE REVIEW

**Comment by zaggino** [comment]
Thanks for the PR, published as `z-schema@4.0.1`

**Comment by santam85** [comment]
Thank you!

**Comment by santam85** [comment]
Sorry @zaggino to bother you again, but we might need to also have a hotfix that supports node v6. Is there a branch were we could merge the required changes for a 3.25.2 release?

**Comment by zaggino** [comment]
@santam85 use 4.0.2

https://github.com/zaggino/z-schema/commit/d0a8d1d2a7422d1bff3fe177c794bce83a5dfea3
https://travis-ci.org/zaggino/z-schema/builds/519263893

only node 4.x doesn't work anymore

**Comment by santam85** [comment]
Yeah, I noticed after my comment that v6 is not really breaking any test on v4, so we should be fine! Thanks again for your quick responses!

**Pull request merged**
