### PR TITLE
Add support for custom validators

### LINKED ISSUE #114: Support for custom validators.
For many use cases JSON Schema isn't enough to check all restrictions.
So right now, typical scenario is validate using JSON schema validator and them use hand-write recursive code.

 Consider following schema:
```json
{
   "definitions": {
       "TestType": {
          "type": "string",
          "description": "Type that should be additionally validated"
       }
   },
   "oneOf" : [
      { "$ref": "#/definitions/TestType" },
      {
        "type": "array",
        "items": { "$ref": "#/definitions/TestType" }
      }
   ]
}
```
So JS validation code would be, like that:
```javascript
function validate(data) {
  if (data.constructor === Array) {
    for (var i = 0; i < data.lenght; i++)
       validateTestType(data);
    return;
  }
  validateTestType(data);
}

function validateTestType(data) {
  //user specific validation
}
```
In real life hand-written validator quickly mirror most of JSON Schema.
It especially hard to work with 'oneOf', 'allOf', etc.
My idea is to allow user to specify additional validators for JSON Schema types.
Syntax could be like following:
```javascript
var valid = validator.validate(json, schema, {
  "#/definitions/TestType": function (report, json) {
     //user specific validation
  }
});
```
It not only simplify code but also significantly improve speed of full validation.
In next couple of days I could prepare PR.
What do you think about such functionality?

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Fixes #114 

@zaggino It took me like forever to implement this.
I experiment with couple generic approaches but all them didn't suit all possible situations. 
So in the end, I just add the simplest possible hook.
And user implement custom mechanism on top of z-schema which fully suit his personal needs.

### CODE REVIEW

**Comment by zaggino** [comment]
@IvanGoncharov can we get a real life (or at least dummy one like in the tests) example to the readme to this feature? it's not obvious how to use it unless you digged and know the z-schema codes. Otherwise it looks fine to me.

**Comment by IvanGoncharov** [comment]
@zaggino 
My use case is too specific, so I need to think of something else for example.
Worst case scenario I will copy-paste example from tests.

**Comment by zaggino** [comment]
Thanks, let me know when it's added and I'll merge & release it.

**Comment by IvanGoncharov** [comment]
@zaggino I added a whole section with real-life example, here is preview:
https://github.com/APIs-guru/z-schema#customvalidator

Grunt also released `1.0.0` version and it's unsupported by some of the plugins, see this:
https://travis-ci.org/zaggino/z-schema/jobs/120954098#L208
So as temporary workaround I limit grunt versions to `0.4.X`.

**Comment by IvanGoncharov** [comment]
@zaggino Thank you :+1:

**Comment by zaggino** [comment]
No worries. Will release as `3.17.0` in a few minutes.

**Comment by zaggino** [comment]
```
Done, without errors.
+ z-schema@3.17.0
```

**Pull request merged**
