### PR TITLE
Fixed report object object error

### PR DESCRIPTION
**Pull request by simon-p-r**
I ran grunt tasks for jscs and they have passed locally.

### CODE REVIEW

**Comment by simon-p-r** [comment]
The jscs settings are is very sensitive, I don't lint.  The new error was also occurring locally for me when trying to run grunt tasks.

**Comment by zaggino** [comment]
You need to run `git submodule update --init` locally. To download `jsonSchemaTestSuite` files.

**Comment by simon-p-r** [comment]
Ok all tests have passed locally, this is my first pull request so can you tell me what I need to do to get this fix committed.

**Comment by zaggino** [comment]
Nothing more, all tests are passing locally and it looks like the rest of the code. The reason behind strict lint settings are that the code will always look like one person wrote it and it's better/easier to read that way. I'll merge this now and release a new version to npm soon.

**Comment by zaggino** [comment]
So that's merged - first pull request done ;-)

**Comment by simon-p-r** [comment]
Thanks

**Comment by zaggino** [comment]
This is now uploaded to npm as version `3.3.2`

**Pull request merged**
