### PR TITLE
Issue #143 failing test

### PR DESCRIPTION
**Pull request by simon-p-r**
Here is failing test with some assertions.

### CODE REVIEW

**Comment by zaggino** [comment]
schema should be directly in `schema: {`, it seems like you put it one level lower ... also what's the `metaSchema` thing? I'd expect the `id` and `type` properties be in the root of the schema. Try validatin your schema with https://github.com/zaggino/z-schema#noextrakeywords and you'll see the problem

**Comment by zaggino** [comment]
See how it's done here for example: https://github.com/zaggino/z-schema/blob/master/test/ZSchemaTestSuite/Issue139.js

**Comment by simon-p-r** [comment]
This test is to show that when an incorrect object is passed to validateSchema function it should evaluate to false and not true like it is currently doing.

**Comment by zaggino** [comment]
But this object is completely correct and equal to an empty schema, because both `schema` and `metaSchema` properties are not defined in JSON schema specification, they are ignored. If you don't want the validator to ignore them, you need to use `noExtraKeywords: true` option.

**Comment by simon-p-r** [comment]
The assertion should be to test if it is valid or not as this object is not valid it should return false.  noExtraKeywords should not be necessary to check if an object is json schema or not

**Comment by zaggino** [comment]
But that object is an valid JSON schema ... even `{}` is an valid JSON schema, that's how the specification is written and that's why I've created options like `noExtraKeywords` and `noTypeless`

**Comment by simon-p-r** [comment]
Maybe I don't understand json schema well enough but I would expect an object which is not a json schema to not be validated as json schema and that includes an empty object.

**Comment by zaggino** [comment]
To be honest, I also found JSON schema spec quite confusing, that's why I invented all the configurable options z-schema has.

**Comment by simon-p-r** [comment]
No problem, I have added some checks to ensure I am validating what I consider to be a valid json schema before calling method.

**Pull request closed without merging**
