### PR TITLE
Removing Request as a dependency

### LINKED ISSUE #173: Gauging Interest in PR for removing Request as dependency
The request library now offers more features than are necessary in z-schema.
There were two total references to it by my measure, one of which is a test ([1](https://github.com/zaggino/z-schema/blob/master/bin/z-schema), [2](https://github.com/zaggino/z-schema/blob/master/test/spec/AutomaticSchemaLoadingSpec.js)).

Removing the dependency and writing nodejs native code was a <20 LOC difference, and should provide equivalent error coverage. I ran grunt and it passed all tests (although I did get 3 validateIndentation errors from jscs in test/spec/schemaPathSpec.js, which was unmodified).

 - Is this something desired?
 - If so, what steps should I follow to build for a PR?

Issue noted here: https://github.com/apigee-127/sway/issues/97

### PR DESCRIPTION
**Pull request by TheToolbox**
Attempting to remove Request as a dependency to close #173 . 
It's worthwhile noting that there's a lot of change in the generated files. 

The grunt script, marked all specs as passing*, so just double check that I didn't change anything I shouldn't have. Thanks.

*I had to use `--force` because there were validateIndentation errors in test/spec/schemaPathSpec.js during jscs:src

### CODE REVIEW

**Comment by TheToolbox** [comment]
Errored out of CI due to those indentation issues. Was that happening in master previously?

**Comment by TheToolbox** [comment]
Fingers crossed ^

**Comment by zaggino** [comment]
You can fix travis to check
```
node_js:
  - "0.10"
  - "4"
  - "6"
```
these should pass

**Comment by TheToolbox** [comment]
The list currently has 0.10, 4, and 5. I'll switch out 5 for 6, but the ones that are failing are 0.10 and 4. Were these previously passing?

**Comment by zaggino** [comment]
if `6` passes, that's fine, I can check the rest

**Comment by TheToolbox** [comment]
Sweet. v6 is passing. Thanks!

**Comment by zaggino** [comment]
👍 thanks for the pr, will release soon

**Comment by zaggino** [comment]
all green -> https://travis-ci.org/zaggino/z-schema/builds/161514886

**Comment by zaggino** [comment]
Version `3.18.0` is now published to npm

**Pull request merged**
