### PR TITLE
Provide option to skip validation errors

### LINKED ISSUE #233: Allow to specify errors to be reported
Hi, @zaggino  It would be nice if we can specify which errors we are interested in to be reported and then skip validations that are not required.

E.G we only care about MISSING_REQUIRED_PROPERTIES, then we dont want to execute the ohter validators except the one for `required`.

### PR DESCRIPTION
**Pull request by vladbarosan**
Fixes #233

### CODE REVIEW

**Comment by vladbarosan** [comment]
@zaggino  if you can have a look, it would be appreciated :)

**Comment by zaggino** [comment]
@vladbarosan code looks ok, but missing
a) readme update
b) at least one simple test

**Comment by vladbarosan** [comment]
@zaggino thanks for the quick review. Addressed the feedback.

**Comment by vladbarosan** [comment]
@zaggino  I added an extra test for when the array is empty to still do all validations. Can you have a look please, we would like to use this feature :)

**Comment by zaggino** [comment]
Published `z-schema@3.26.0`

**Comment by zaggino** [comment]
`npm unpublish z-schema@3.26.0` is it breaks in Node v4

**Comment by zaggino** [comment]
Published `z-schema@4.0.0`, no feature changes, just dropped support for old node.js versions.
https://github.com/zaggino/z-schema/commit/cddefc5788982e9cde586b675e6a7f2642300556

**Pull request merged**
